/* Config.hh. Generated by CMake for ignition-physics. */

#ifndef IGNITION_PHYSICS_CONFIG_HH_
#define IGNITION_PHYSICS_CONFIG_HH_

/* Version number */
#define IGNITION_PHYSICS_MAJOR_VERSION 2
#define IGNITION_PHYSICS_MINOR_VERSION 1
#define IGNITION_PHYSICS_PATCH_VERSION 0

#define IGNITION_PHYSICS_VERSION "2.1"
#define IGNITION_PHYSICS_VERSION_FULL "2.1.0"

#define IGNITION_PHYSICS_ENGINE_INSTALL_DIR "/home/claire/citadel_ws/src/ign-physics/install/lib/ign-physics-2/engine-plugins"

#endif
