name: Ubuntu Bionic CI

on: [push, pull_request]

jobs:
  bionic-ci:
    runs-on: ubuntu-latest
    name: Ubuntu Bionic CI
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Bionic CI
        id: ci
        uses: ignition-tooling/ubuntu-bionic-ci-action@master
        with:
          apt-dependencies: |
            dart6-data
            libbenchmark-dev
            libdart6-collision-ode-dev
            libdart6-dev
            libdart6-utils-urdf-dev
            libeigen3-dev
            libignition-cmake2-dev
            libignition-common3-dev
            libignition-math6-dev
            libignition-math6-eigen3-dev
            libignition-plugin-dev
            libsdformat10-dev
            software-properties-common
          codecov-token: ${{ secrets.CODECOV_TOKEN }}
