name: Ubuntu Bionic CI

on: [push, pull_request]

jobs:
  bionic-ci:
    runs-on: ubuntu-latest
    name: Ubuntu Bionic CI
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Bionic CI
        id: ci
        uses: ignition-tooling/ubuntu-bionic-ci-action@master
        with:
          apt-dependencies: 'software-properties-common libignition-cmake2-dev libignition-common3-dev libignition-math6-dev libignition-math6-eigen3-dev libignition-plugin-dev libeigen3-dev dart6-data libdart6-collision-ode-dev libdart6-dev libdart6-utils-urdf-dev libbenchmark-dev libsdformat9-dev'
          codecov-token: ${{ secrets.CODECOV_TOKEN }}
