name: Ubuntu CI

on:
  pull_request:
  push:
    branches:
      - 'ign-physics[0-9]'
      - 'gz-physics[1-9]?[0-9]'
      - 'main'

jobs:
  jammy-ci:
    runs-on: ubuntu-latest
    name: Ubuntu Jammy CI
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Compile and test
        id: ci
        uses: gazebo-tooling/action-gz-ci@jammy
        with:
          codecov-enabled: true
          cppcheck-enabled: true
          cpplint-enabled: true
  noble-ci:
    runs-on: ubuntu-latest
    name: Ubuntu Noble CI
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Compile and test
        id: ci
        uses: gazebo-tooling/action-gz-ci@noble
